package entity;
// Generated Aug 2, 2017 4:18:40 PM by Hibernate Tools 4.3.1



/**
 * Book generated by hbm2java
 */
public class Book  implements java.io.Serializable {


     private Integer id;
     private Genre genre;
     private Author author;
     private Publisher publisher;
     private String name;
     private byte[] content;
     private Integer pageCount;
     private String isbn;
     //private Integer authorId;
     private Integer publishYear;
     //private Integer publisherId;
     private byte[] image;
     private String descr;
     private String bookcol;

     private boolean edit=false;
         public boolean isEdit() {
        return edit;
    }

    public void setEdit(boolean edit) {
        this.edit = edit;
    }
    
     
     
    public Book() {
    }

    public Book(Genre genre,Author author, Publisher publisher, String name, byte[] content, Integer pageCount, String isbn/*, Integer authorId*/, Integer publishYear, /*Integer publisherId,*/ byte[] image, String descr, String bookcol) {
       this.genre = genre;
       this.author = author;
       this.publisher = publisher;
       this.name = name;
       this.content = content;
       this.pageCount = pageCount;
       this.isbn = isbn;
       //this.authorId = authorId;
       this.publishYear = publishYear;
       //this.publisherId = publisherId;
       this.image = image;
       this.descr = descr;
       this.bookcol = bookcol;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Publisher getPublisher() {
        return publisher;
    }

    public void setPublisher(Publisher publisher) {
        this.publisher = publisher;
    }
    
    
    
    public Author getAuthor() {
        return this.author;
    }
    
    public void setAuthor(Author author) {
        this.author = author;
    }
    
    public Genre getGenre() {
        return this.genre;
    }
    
    public void setGenre(Genre genre) {
        this.genre = genre;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public byte[] getContent() {
        return this.content;
    }
    
    public void setContent(byte[] content) {
        this.content = content;
    }
    public Integer getPageCount() {
        return this.pageCount;
    }
    
    public void setPageCount(Integer pageCount) {
        this.pageCount = pageCount;
    }
    public String getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }
    /*public Integer getAuthorId() {
        return this.authorId;
    }
    
    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }*/
    public Integer getPublishYear() {
        return this.publishYear;
    }
    
    public void setPublishYear(Integer publishYear) {
        this.publishYear = publishYear;
    }/*
    public Integer getPublisherId() {
        return this.publisherId;
    }
    
    public void setPublisherId(Integer publisherId) {
        this.publisherId = publisherId;
    }*/
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }
    public String getDescr() {
        return this.descr;
    }
    
    public void setDescr(String descr) {
        this.descr = descr;
    }
    public String getBookcol() {
        return this.bookcol;
    }
    
    public void setBookcol(String bookcol) {
        this.bookcol = bookcol;
    }




}


