package entity;
// Generated Aug 2, 2017 4:18:40 PM by Hibernate Tools 4.3.1



/**
 * Publisher generated by hbm2java
 */
public class Publisher  implements java.io.Serializable {


     private Integer id;
     private String name;

    public Publisher() {
    }

    public Publisher(String name) {
       this.name = name;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


